name: t_store_admin_panel
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

#--------------- PACKAGES ---------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  intl: ^0.20.2
  logger: ^2.5.0
  lottie: ^3.3.1
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1
  flutter_dropzone: ^4.2.1
  flutter_typeahead: ^5.2.0
  connectivity_plus: ^6.1.4
  multi_select_flutter: ^4.1.3
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1

  # Web Specific
  web: ^1.1.1
  http: ^1.3.0 
  fl_chart: ^1.0.0
  data_table_2: ^2.6.0
  url_strategy: ^0.3.0
  universal_html: ^2.2.4

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Firebase
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.9
  cloud_firestore: ^5.6.8

  # Supabase
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  #--------------- LOCAL ASSETS -------------#
  assets:
    - assets/logos/
    - assets/images/contents/
    - assets/images/user/
    - assets/images/animations/
    - assets/Icons/payment_methods/
    - .env

  

  #--------------- LOCAL FONTS -------------#
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
