// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlBwXQ8RcOkWiJH0MeCieKJgG6Z-l1tF4',
    appId: '1:13711680757:web:8d9e3b94a98f560ed991bc',
    messagingSenderId: '13711680757',
    projectId: 'ecommerceapp-b6acf',
    authDomain: 'ecommerceapp-b6acf.firebaseapp.com',
    storageBucket: 'ecommerceapp-b6acf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDLSNEHg8ZW1W_n1eChXBdu9xXKSCsdpw',
    appId: '1:13711680757:android:1e66bfebc11bd936d991bc',
    messagingSenderId: '13711680757',
    projectId: 'ecommerceapp-b6acf',
    storageBucket: 'ecommerceapp-b6acf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcOfs3lVCcK8u5s6C55BNTdO0lJHXIeBo',
    appId: '1:13711680757:ios:23fdff6a14ed4338d991bc',
    messagingSenderId: '13711680757',
    projectId: 'ecommerceapp-b6acf',
    storageBucket: 'ecommerceapp-b6acf.firebasestorage.app',
    androidClientId: '13711680757-sl96imq945hodnscn12d8nv3gf7ru1d5.apps.googleusercontent.com',
    iosClientId: '13711680757-l6duoemgg9m95ptmvgimkudae7lvoij7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStoreAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlBwXQ8RcOkWiJH0MeCieKJgG6Z-l1tF4',
    appId: '1:13711680757:web:f99bb866f4d4505dd991bc',
    messagingSenderId: '13711680757',
    projectId: 'ecommerceapp-b6acf',
    authDomain: 'ecommerceapp-b6acf.firebaseapp.com',
    storageBucket: 'ecommerceapp-b6acf.firebasestorage.app',
  );
}
